# Netlify configuration file for deploying a Python application

[build]
  publish = "static"  # Directory to publish
  command = "python app.py"  # Command to run your application

[dev]
  command = "python app.py"  # Command to run your application in development mode

